# How long between each heartbeat the client sends to the rover (in seconds)
float32 heartbeat_interval

# How long to wait for a heartbeat response from the rover (in seconds)
float32 heartbeat_timeout

# How many times to retry a heartbeat before giving up
uint32 heartbeat_fail_limit
---
bool success