version: "3.9"

services:
  micro-ros-agent:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/ttyUSB0
    privileged: true
    network_mode: "host"
    pid: "host"
  ros_echo:
    build:
      context: ../..
      dockerfile: docker_scripts/jetson/jetsonDockerfile
    network_mode: "host"
    pid: "host"
    command: tail -F anything # will run container forever
    # depends_on:
    #   - micro-ros-agent
  realsense_ros2:
      #target: librealsense
    tty: true
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'