version: "2"

services:
  micro-ros-agent:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/ttyUSB0
    privileged: true
    network_mode: "host"
    pid: "host"
  rover_main:
    build:
      context: ../..
      dockerfile: docker_scripts/jetson/jetsonDockerfile
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    network_mode: "host"
    pid: "host"
    command: tail -F anything
